#!/bin/bash

cp -r ~/.config ~/.config_old
rm -rf ~/.config/alacritty; ln -s $(pwd)/alacritty/ ~/.config/alacritty
rm -rf ~/.config/bash; ln -s $(pwd)/bash/ ~/.config/bash
rm -rf ~/.config/compton; ln -s $(pwd)/compton/ ~/.config/compton
rm -rf ~/.config/fish; ln -s $(pwd)/fish/ ~/.config/fish
rm -rf ~/.config/git; ln -s $(pwd)/git/ ~/.config/git
rm -rf ~/.config/htop; ln -s $(pwd)/htop/ ~/.config/htop
rm -rf ~/.config/i3; ln -s $(pwd)/i3/ ~/.config/i3
rm -rf ~/.config/nvim; ln -s $(pwd)/nvim/ ~/.config/nvim
rm -rf ~/.config/ptpython; ln -s $(pwd)/ptpython/ ~/.config/ptpython
rm -rf ~/.config/rofi; ln -s $(pwd)/rofi/ ~/.config/rofi
rm -rf ~/.config/tmux; ln -s $(pwd)/tmux/ ~/.config/tmux

mkdir ~/.install

# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.install/fzf
# ~/.install/fzf/install

# curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
# 	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# git clone https://github.com/pyenv/pyenv.git ~/.install/pyenv

