#!/bin/bash

sudo apt update
sudo apt install git
sudo apt install curl
sudo apt install neovim
sudo apt install gcc
sudo apt install make
sudo apt install zlib1g-dev

mkdir ~/.install

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.install/fzf
~/.install/fzf/install

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

git clone https://github.com/pyenv/pyenv.git ~/.install/pyenv

