#!/usr/bin/fish

alias g="git"
alias aw="arch-wiki"
alias bc="bc -q"
alias ls="exa --long --icons --group-directories-first"
alias tree="exa -T --group-directories-first"
# alias p="ptpython --config-dir=~/.config/ptpython"
alias p="ptpython"
alias m="musikcube"
alias htop="export TERM=screen-256color;/usr/local/bin/htop;export TERM=tmux-256color"
alias jc="cd ~/.config"
alias jcn="cd ~/.config/nvim"
alias jv="cd ~/.config/nvim"
alias jp="cd ~/.config/nvim/lua/ampersand/plugins"
alias jg="cd ~/git"
alias gs="git status"
alias gf="git fetch"
alias gp="git pull"
alias gP="git push"
alias gss="gita ll"
alias plz="sudo $history[1]"
alias lg="lazygit"
# alias br="make build; make run"
alias tt="taskwarrior-tui"
alias taskopen="taskopen -c ~/.config/task/taskopen"
alias d="br"

alias :e="config_vim"

