#!/bin/bash

_update_ps1() {
	EXIT=$?
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;'$([ $USER = root ] && echo 31 || echo 32)'m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w'$([ $EXIT -ne 0 ] && echo "\[\033[01;31m\] $EXIT\[\033[01;34m\]")' \$\[\033[00m\] ';
}

PROMPT_COMMAND="_update_ps1";

