#!/bin/bash

export EDITOR=nvim # Set the editor to neovim
export HJKL=1 # Controls the movement keys in my programs
# export LS_COLORS=$LS_COLORS'di=0;34:ex=0;92:ln=0;96:cd=0;93:bd=0;93:';
# export LS_COLORS=$LS_COLORS:'di=0;34:ex=0;163:ln=0;96:cd=0;93:bd=0;93:';
# export LS_COLORS='di=0;163:ex=0;163:ln=0;163:cd=0;163:bd=0;163:';

if [ -d ~/.install/pyenv ]; then
	export PYENV_ROOT="$HOME/.install/pyenv";
	export PATH="$PYENV_ROOT/bin:${PATH}";
	export PATH="$PYENV_ROOT/shims:${PATH}";
fi

[ -f ~/.config/bash/bash_ps1 ] && . ~/.config/bash/bash_ps1;
[ -f ~/.install/fzf/fzf.bash ] && source ~/.install/fzf/fzf.bash;
