#!/bin/bash

alias ipython="ipython -i --no-banner"
alias bpython="bpython -iq"

alias hideFiles="defaults write com.apple.finder AppleShowAllFiles NO;killall Finder"

alias showFiles="defaults write com.apple.finder AppleShowAllFiles YES;killall Finder"

alias fixTwitch="echo '\$(\"div#ember2659>div>div.flex__item.flex--verticalCenter\").remove()' | pbcopy"

alias asar="/Users/cooperanderson/node_modules/asar/bin/asar"

alias editProfile="open -a TextEdit ~/.bash_profile"

alias blockade="/Users/cooperanderson/Google\ Drive/Other/Programming/JetBrains/WebStorm/Blockade/run.sh"

alias blessed="/Users/cooperanderson/Google\ Drive/Other/Programming/JetBrains/WebStorm/blessed-test/run.sh"

alias killIcons="cd /Users/cooperanderson/Google\ Drive/Programming;find . -name 'Icon*' -type f -delete"

alias killIcons2="cd /Users/cooperanderson/Google\ Drive/GitHub;find . -name 'Icon*' -type f -delete"

alias killBluetooth="sudo rm -R /Library/Preferences/com.apple.bluetooth.plist"

alias nnn="nnn -l"

# alias gitFiles="cd /Users/cooperanderson/Google\ Drive/GitHub"

alias ls="ls -G"

alias comp="lua /Stupid/cc-emu/cli.lua /Stupid/cc-emu/computers/0"

alias td="tudu -c ~/.config/tudu/tudurc -f ~/.config/tudu/tudu.xml"

alias btc="coinmon -p .config/coinmon/portfolio.json -s 0,1,2,3,4,7"

alias alacritty="/Applications/Alacritty.app/Contents/MacOS/alacritty"

alias tmux="tmux -f ~/.config/tmux/tmux.conf"

