#!/bin/bash

fd() {
	# local dir;
	dir=$(find ${1:-.} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
	cd "$dir";
}

vim() {
	nvim $@;
}

vot() {
	CURRENT_DIRECTORY=$(pwd);
	cd ~/.config;
	SELECTED_FILE=$(fzf);
	if [ $? -ne 130 ]; then
		if [ -z $EDITOR ]; then
			vim $SELECTED_FILE;
		else
			$EDITOR $SELECTED_FILE;
		fi
	fi
	cd $CURRENT_DIRECTORY;
}

curl() {
	$(which curl) $@;
	echo;
}

p() {
	ptpython --config-dir=~/.config/ptpython $@;
}

