
# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[ -z "$TMUX" ] && export TERM="xterm-256color"
# export TERM=screen-256color
# alias tmux='tmux -2'  # for 256color
# alias tmux='tmux -u'  # to get rid of unicode rendering problem

alias hideFiles="defaults write com.apple.finder AppleShowAllFiles NO;killall Finder"

alias showFiles="defaults write com.apple.finder AppleShowAllFiles YES;killall Finder"

alias fixTwitch="echo '\$(\"div#ember2659>div>div.flex__item.flex--verticalCenter\").remove()' | pbcopy"

alias asar="/Users/cooperanderson/node_modules/asar/bin/asar"

alias editProfile="open -a TextEdit ~/.bash_profile"

alias electron="/Applications/Electron.app/Contents/MacOS/Electron"

alias blockade="/Users/cooperanderson/Google\ Drive/Other/Programming/JetBrains/WebStorm/Blockade/run.sh"

alias blessed="/Users/cooperanderson/Google\ Drive/Other/Programming/JetBrains/WebStorm/blessed-test/run.sh"

alias killIcons="cd /Users/cooperanderson/Google\ Drive/Programming;find . -name 'Icon*' -type f -delete"

alias killIcons2="cd /Users/cooperanderson/Google\ Drive/GitHub;find . -name 'Icon*' -type f -delete"

alias killBluetooth="sudo rm -R /Library/Preferences/com.apple.bluetooth.plist"

# alias gitFiles="cd /Users/cooperanderson/Google\ Drive/GitHub"

fd() {
	local dir
	dir=$(find ${1:-.} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
	cd "$dir"
}

gh() {
	cd ~/GitHub;
	fd;
}

# alias gh="cd ~/Github"

alias ipython="ipython --no-banner"

alias cc-emu="lua /Users/cooperanderson/Library/Application\ Support/cc-emu/cli.lua /Users/cooperanderson/Library/Application\ Support/cc-emu/computers/0"

alias colortest='for i in {0..255} ; do
    printf "\x1b[38;5;${i}m%3d " "${i}"
    if (( $i == 15 )) || (( $i > 15 )) && (( ($i-15) % 12 == 0 )); then
        echo;
    fi
done'

# alias vim="/usr/local/Cellar/vim/8.0.0600/bin/vim"
# alias vim7="/usr/bin/vim"
vim() {
	$(brew --prefix vim)/bin/vim $@; # /usr/local/Cellar/vim/8.0.0600/bin/vim $@;
}

vim7() {
	/usr/bin/vim $@;
}

# EMOJI_LIST=(🐙 🎹 😀 👾 👌 🎩 🐽 🚀 ⌚️ 🕹 💻);
# RANDOM_EMOJI=${EMOJI_LIST[$((RANDOM%${#EMOJI_LIST[@]}))]};
# PS1="\[$(tput setaf 3)\]\w\[$(tput sgr0)\]\n$RANDOM_EMOJI  \$ "

export PATH

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/cooperanderson/Downloads/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/cooperanderson/Downloads/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/cooperanderson/Downloads/google-cloud-sdk/completion.bash.inc ]; then
  source '/Users/cooperanderson/Downloads/google-cloud-sdk/completion.bash.inc'
fi

# added by Anaconda2 4.2.0 installer
# export PATH="/Users/cooperanderson/Library/Preferencess/anaconda2/bin:$PATH"
# eval $(/usr/libexec/path_helper -s)

. /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

defaults write org.python.python ApplePersistenceIgnoreState NO

alias ls="ls -G"

# vimBrew=/usr/local/Cellar/vim/8.0.0596/bin/vim
# alias vim7="/usr/bin/vim"
# alias vim8="$vimBrew"
# function vim() { tmux new-session -d '/usr/local/Cellar/vim/8.0.0596/bin/vim $@';tmux a ;}

# function vim() { tmux new-session -d "$vimBrew $@";tmux a ;}
